// Hard-coded department data for the database
// Names are unabbreviated and are generally from the registrar's course offerings site

module.exports = [
  { _id: 'AAS', name: 'African American Studies' },
  { _id: 'AFS', name: 'African Studies' },
  { _id: 'AMS', name: 'American Studies' },
  { _id: 'ANT', name: 'Anthropology' },
  { _id: 'AOS', name: 'Atmospheric and Oceanic Sciences' },
  { _id: 'APC', name: 'Applied and Computational Mathematics' },
  { _id: 'ARA', name: 'Arabic' },
  { _id: 'ARC', name: 'Architecture' },
  { _id: 'ART', name: 'Art and Archaeology' },
  { _id: 'ASA', name: 'Asian American Studies' },
  { _id: 'AST', name: 'Astrophysical Sciences' },
  { _id: 'ATL', name: 'Atelier' },
  { _id: 'BCS', name: 'Bosnian-Croatian-Serbian' },
  { _id: 'CBE', name: 'Chemical and Biological Engineering' },
  { _id: 'CEE', name: 'Civil and Environmental Engineering' },
  { _id: 'CGS', name: 'Cognitive Science' },
  //{ _id: 'CHE', name: 'Chemical Engineering' }, // this is a guess
  { _id: 'CHI', name: 'Chinese' },
  { _id: 'CHM', name: 'Chemistry' },
  { _id: 'CHV', name: 'Center for Human Values' },
  { _id: 'CLA', name: 'Classics' },
  { _id: 'CLG', name: 'Classical Greek' },
  { _id: 'COM', name: 'Comparative Literature' },
  { _id: 'COS', name: 'Computer Science' },
  { _id: 'CTL', name: 'Center for Teaching and Learning' },
  { _id: 'CWR', name: 'Creative Writing' },
  { _id: 'CZE', name: 'Czech' },
  { _id: 'DAN', name: 'Dance' },
  { _id: 'EAS', name: 'East Asian Studies' },
  { _id: 'ECO', name: 'Economics' },
  { _id: 'ECS', name: 'European Cultural Studies' },
  { _id: 'EEB', name: 'Ecology and Evolutionary Biology' },
  { _id: 'EGR', name: 'Engineering' },
  { _id: 'ELE', name: 'Electrical Engineering' },
  { _id: 'ENE', name: 'Energy Studies' },
  { _id: 'ENG', name: 'English' },
  { _id: 'ENT', name: 'Entrepreneurship' },
  { _id: 'ENV', name: 'Environmental Studies' },
  { _id: 'EPS', name: 'Contemporary European Politics' },
  { _id: 'FIN', name: 'Finance' },
  { _id: 'FRE', name: 'French' },
  { _id: 'FRS', name: 'Freshman Seminars' },
  { _id: 'GEO', name: 'Geosciences' },
  { _id: 'GER', name: 'German' },
  { _id: 'GHP', name: 'Global Health and Health Policy' },
  { _id: 'GLS', name: 'Global Seminar' },
  { _id: 'GSS', name: 'Gender and Sexuality Studies' },
  { _id: 'HEB', name: 'Hebrew' },
  { _id: 'HIN', name: 'Hindi' },
  { _id: 'HIS', name: 'History' },
  { _id: 'HLS', name: 'Hellenic Studies' },
  { _id: 'HOS', name: 'History of Science' },
  { _id: 'HPD', name: 'History and Practice of Diplomacy' }, // this is new?
  { _id: 'HUM', name: 'Humanistic Studies' },
  { _id: 'ISC', name: 'Integrated Science Curriculum' },
  { _id: 'ITA', name: 'Italian' },
  { _id: 'JDS', name: 'Judaic Studies' },
  { _id: 'JPN', name: 'Japanese' },
  { _id: 'JRN', name: 'Journalism' },
  { _id: 'KOR', name: 'Korean' },
  { _id: 'LAO', name: 'Latino Studies' },
  { _id: 'LAS', name: 'Latin American Studies' },
  { _id: 'LAT', name: 'Latin' },
  { _id: 'LCA', name: 'Lewis Center for the Arts' },
  { _id: 'LIN', name: 'Linguistics' },
  { _id: 'MAE', name: 'Mechanical and Aerospace Engineering' },
  { _id: 'MAT', name: 'Mathematics' },
  { _id: 'MED', name: 'Medieval Studies' },
  { _id: 'MOD', name: 'Media and Modernity' },
  { _id: 'MOG', name: 'Modern Greek' },
  { _id: 'MOL', name: 'Molecular Biology' },
  { _id: 'MSE', name: 'Materials Science and Engineering' },
  { _id: 'MTD', name: 'Music Theater' },
  { _id: 'MUS', name: 'Music' },
  { _id: 'NES', name: 'Near Eastern Studies' },
  { _id: 'NEU', name: 'Neuroscience' },
  { _id: 'ORF', name: 'Operations Research and Financial Engineering' },
  { _id: 'PAW', name: 'Ancient World' },
  { _id: 'PER', name: 'Persian' },
  { _id: 'PHI', name: 'Philosophy' },
  { _id: 'PHY', name: 'Physics' },
  { _id: 'PLS', name: 'Polish' },
  { _id: 'POL', name: 'Politics' },
  { _id: 'POP', name: 'Population Studies' },
  { _id: 'POR', name: 'Portuguese' },
  { _id: 'PSY', name: 'Psychology' },
  { _id: 'QCB', name: 'Quantitative Computational Biology' },
  { _id: 'REL', name: 'Religion' },
  { _id: 'RES', name: 'Russian, East European, Eurasian' },
  { _id: 'RUS', name: 'Russian' },
  { _id: 'SAN', name: 'Sanskrit' },
  { _id: 'SAS', name: 'South Asian Studies' },
  { _id: 'SLA', name: 'Slavic Languages and Literature' },
  { _id: 'SML', name: 'Statistics and Machine Learning' },
  { _id: 'SOC', name: 'Sociology' },
  { _id: 'SPA', name: 'Spanish' },
  //{ _id: 'SPO', name: 'Spanish' }, // is this a typo?
  { _id: 'STC', name: 'Science and Technology Council' },
  { _id: 'SWA', name: 'Swahili' },
  { _id: 'THR', name: 'Theater' },
  { _id: 'TPP', name: 'Teacher Preparation' },
  { _id: 'TRA', name: 'Translation, Intercultural Communication' },
  { _id: 'TUR', name: 'Turkish' },
  { _id: 'TWI', name: 'Twi' },
  { _id: 'URB', name: 'Urban Studies' },
  { _id: 'URD', name: 'Urdu' },
  { _id: 'VIS', name: 'Visual Arts' },
  //{ _id: 'WOM', name: 'Gender Studies' }, // this is a guess
  { _id: 'WRI', name: 'Princeton Writing Program' },
  { _id: 'WWS', name: 'Woodrow Wilson School' }
];
